### ISSUE TITLE
Meta-functions as named arrows

### ISSUE THREAD

**Issue by casper-bach** [metaborg/dynsem#75]
Can we explicate meta-functions as named arrows instead of overloaded
default arrows?

Consider:

```
  constructors
    concat: String * String --> String

  rules
    concat(s1, s2) --> prim_concat(s1, s2)
```

Using the current scheme, this meta-function is explicated as an
overloaded default arrow:

```
  sorts
    concat__Arrow

  constructors
    concat : String * String -> concat__Arrow {meta-function}

  arrows
    concat__Arrow -default-> String

  rules
    concat__Arrow(s1, s2) -default-> prim_concat(s1, s2)
```

Could we model meta-functions as a named arrow instead?:

```
  arrows
    String * String -concat-> String

  rules
    (s1, s2) -concat-> prim_concat(s1, s2)
```

And simply treat:

```
  concat(s1, s2) --> s
```

as syntactic sugar for?:

```
  (s1, s2) -concat-> s
```

This strikes me as cleaner, and will improve the quality of generated
Coq code, since we can map meta-functions onto built-in Coq relations (or functions)
more easily, without having to un-overload arrows and avoid the (I
think) artificial sort `concat__Arrow`.

**Comment by eelcovisser** [comment]
Yes. This requires that we have tuples. Meta-functions are motivated by (1) the lack of tuples, which requires such an arrow to apply to a auxiliary constructor, which is rather ugly, and (2) concise application of an arrow; we can only apply arrows in a premise (x, y) -concat-> z, instead of applying it in a term StringV(concat(x, y)).

Of course, this is not a good example since the only thing concat does is call a primitive operation. So, it can be applied directly through prim_concat.

**Comment by vvergu** [comment]
Hi. As @eelcovisser points out we won't be able to rely on implicit reductions to nest meta-function applications anymore. On the other hand, one could still write:

```
StringV(concat(x, y)).
```

as syntactic sugar for:

```
... --> StringV(s)
where
   (x, y) -concat-> s.
```

I think it's important to have as little concrete syntax alternatives in DynSem as possible. In other words, the more different things look the same in DynSem, the easier it is to (1) evolve a specification and (2) to evolve DynSem itself. The motivation for (1) is that `StringV(concat(x, y))` doesn't say whether `concat(String, String)` is a native operator, a meta-function, or a method call on a native data type. In fact, issue #50 tracks the task of changing the current syntax for function calls on native data types to look the same a constructor application.

But, i acknowledge that:
- tuples are a necessity in general (#58).
- analysis should probably have direct support for meta-functions instead of requiring meta-functions to be desugared

Re. Coq transformation. Why don't we implement transformations from DynSem Core to DS4Coq to change the AST so that it's easier to map to Coq concepts?

This is what i do when i go to an interpretable specification. Some of the transformations produce ASTs that don't have a DynSem concrete syntax representation.

**Comment by casper-bach** [comment]
Seems there are good reasons for preferring meta-functions as overloaded arrows. Closing issue.

I've created a new, somewhat related, issue about overloaded arrows and explication (#86).
